
on:
  workflow_dispatch:        # can be triggered manually
  push:
    branches:
      - main                # run for the main branch
  pull_request:             # and for PRs
                            # other branches that want testing must create a PR

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - name: Install packages
        run: pip install jupyterlab

      - name: Get conjure
        run: |
            wget --quiet --no-check-certificate -c https://github.com/conjure-cp/conjure/releases/download/v2.5.1/conjure-v2.5.1-linux-with-solvers.zip
            unzip -q -o conjure-v2.5.1-linux-with-solvers.zip
            cp -r conjure-v2.5.1-linux-with-solvers/* /usr/local/bin

      - name: Install conjure-notebook
        run: pip install .

      - name: Run tests
        run: cd test && ./run_tests.sh
